project_id = "desafio-focon"
db_url = "postgresql://postgres:postgres@127.0.0.1:54322/postgres"
api_url = "http://127.0.0.1:54321"
s3_host = "127.0.0.1"
s3_protocol = "http"
s3_port = 54321

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_signups = false
